name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run unit tests
        working-directory: ./server
        run: npm run test
      
      #- name: Run e2e tests
      #  working-directory: ./server
      #  run: npm run test:e2e
      
      - name: lint code
        working-directory: ./server
        run: npm run lint
